project:
  type: website
  output-dir: docs

website:
  title: "inti-documentation.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - js_checkpoint7.qmd
      - js_checkpoint8.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

